language: python
sudo: required
dist: xenial

python:
- '3.5'
- '3.6'
- '3.7'

install:
- pip install .
- pip install pytest pytest-cov coveralls

script:
- pytest --cov=urdfpy tests

after_success:
- coveralls || true

deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: UQM21roQPjm82x9h1seze9NlkDWEubzrmru72+bf89oOW7l2ZFhJANdAFO/tLH/vQL6/I8/SOpQn5U/d74h6yhsgoNAYioA0U6QRKNJMLnX2vJIucK0gdalEeTj9Pjiz6a9hVZsrMVjOQoTxe9vU/v2CZ2N+4WkFsXIRNHU7jg+MIprUbAew+ASpSdM5fM404CQFgqbiLK8J3HctV/onG2XBYAS9psYnmc0KNHaw4bqJGZcl1qH+A04a+B0zDZQy02WM7gd2FWycD+0grV2ytevKfV8fEHaUEyzXZq7bhdyoA4CuwIES2DVUZvfRYdDzKqCfJmTsWgpbbOZExuffnN80FaqbiN4feIjLaefVm0Eu4xNNBjG+fgoajqydBDrEsLCML+7OOdkd6RA6vW7ol1Jjb+4G27ZvCe5gwKoMPckDY8FCgMau9mzsr+wLZ9L3WoyaEecTTapFeE/FZOo6CkhHFPRwNAaSWvni6RHb7GVazkbUkAvPH+SyjtxTehoqY1j+8vjHx/VjR4q6ttjk8cfuEPq0q2kX47M2k5/Lk+cAv9dOuJtFIOle3JHV0e2SHIBxvcF43oc29ibG16RLZkmzQbkIww+zPbyAXpV1BKUA60/JzLZicOxpBwKfJa16I6ln9o5804e/kTI7aXmX76vzodsr2WqeJ9d3Z/5kDL8=
  distributions: sdist bdist_wheel
notifications:
  email: false
